### ISSUE TITLE
Caching fails when package have dependencies.

### ISSUE THREAD

**Issue by alirezatheh** [office-tecoli/actions-use-apt-tools#2]
Hi @kaz-utashiro,
I tried to cache `mkvtoolnix` and it seemed that the caching was successful, but when I tried to use `mkvtoolnix` turned out that it's dependencies was not cached.
```
mkvmerge: error while loading shared libraries: libFLAC.so.8: cannot open shared object file: No such file or directory
```

**Comment by kaz-utashiro** [comment]
Did you try "method: timestamp"?
This action caches the output of "dpkg -L" by default.
Failing workflow and result would be helpful.
