### ISSUE TITLE
apt-get update before caching

### ISSUE THREAD

**Issue by iloveitaly** [office-tecoli/actions-use-apt-tools#4]
[I recently learned](https://github.com/catthehacker/docker_images/issues/138#issuecomment-2509889885) that the GitHub action environment (a) updates every week or so (b) does not clear the apt indexes. This is why `apt-get install` works without updating a cache.

However, if you are using a runner outside of GHA (like `act`) this does not work and `apt-get update` needs to be run.

I'm curious if we could add `apt-get update` to this action to make it compatible with act and other non-GHA runners.

wdyt?

**Comment by kaz-utashiro** [comment]
Yes, that is a very reasonable suggestion.
I should have already thought of that.

It seems 30c3259 patch is working, and I will update the version if there are no other problems.
Please tell me if you notice anything.

**Comment by kaz-utashiro** [comment]
Release v1.4 as v1.
https://github.com/tecolicom/actions-use-apt-tools/releases/tag/v1.4

**Comment by iloveitaly** [comment]
awesome, thank you!
