### ISSUE TITLE
failing on ubuntu-24.04

### ISSUE THREAD

**Issue by iloveitaly** [office-tecoli/actions-use-apt-tools#5]
Here's the failure log: https://github.com/iloveitaly/python-starter-template/actions/runs/12281012627/job/34268829894

This version will soon be the default: https://github.com/actions/runner-images/issues/10636

Looks like something with the tar caching is causing the issue:

```
tar: diverted by base-files to\: /bin.usr-is-merged: Cannot stat: No such file or directory
```

**Comment by kaz-utashiro** [comment]
Thank you.  I updated the action to archive only existing files.
Hope it works.
